---
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        args: [--config=pyproject.toml]
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: system
        args: [--fix, --config=pyproject.toml]
      - id: pycln
        name: pycln
        entry: pycln --config=pyproject.toml
        language: system
        types: [python]
      - id: sqlformat
        name: sqlformat
        description: Reformats SQL files using sqlparse
        entry: >-
          bash -c '
          for file in "$@"; do
            sqlformat "$file" \
              --keywords=upper \
              --identifiers=upper \
              --use_space_around_operators \
              -o "$file";
          done' --
        language: system
        types: [sql]
      - id: yamllint
        name: yamllint
        description: Checks YAML file formatting
        entry: yamllint
        language: system
        types: [yaml]
        args: [--format, parsable, --strict]
      - id: yamlfix
        name: yamlfix
        entry: yamlfix
        language: python
        language_version: python3
        types: [yaml]
      - id: jsonlint
        name: jsonlint
        description: Checks JSON file formatting
        entry: jsonlint
        language: system
        types: [json]
      - id: codespell
        name: codespell
        entry: codespell
        language: system
        args:
          - --ignore-words-list
          - sql
          - --skip
          - "*.ipynb"
          - --quiet-level
          - "3"
        exclude: \.(png|jpg|gif|pdf|bin|log)$
ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
